name: tailor_made
description: Tailor-Made with love.

dependencies:
  flutter:
    sdk: flutter
  carousel: ^0.0.1
  firebase_analytics: ^1.0.1
  cloud_firestore: ^0.7.3
  cloud_functions: ^0.0.1
  image_picker: ^0.4.5
  firebase_storage: ^0.3.7
  firebase_auth: ^0.5.11
  intl: ^0.15.6
  url_launcher: ^3.0.2
  photo_view: ^0.0.2
  cached_network_image: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/images/

fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Thin.ttf
        weight: 100
      - asset: assets/fonts/Raleway-Light.ttf
        weight: 300
      - asset: assets/fonts/Raleway-Regular.ttf
        weight: 400
      - asset: assets/fonts/Raleway-Medium.ttf
        weight: 500
      - asset: assets/fonts/Raleway-SemiBold.ttf
        weight: 600
